profile: stand-alone

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bp_database
    username: bpuser
    password: bppassword
  ssl:
    bundle:
      jks:
        web:
          key:
            alias: "People Register Dev"
            password: ""
          keystore:
            location: "classpath:application.p12"
            password: "secret"
            type: "PKCS12"
        server:
          key:
            alias: "People Register Dev"
            password: ""
          keystore:
            location: "classpath:application.p12"
            password: "secret"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.p12"
            password: "secret"
            type: "PKCS12"
server:
  port: 8443
  ssl:
    bundle: web

