# INFO ENDPOINT CONFIGURATION
info.app:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  encoding: '@project.build.sourceEncoding@'
  java.vendor: "@java.vendor@"
  java.version: '@java.version@'

logging:
  level:
    root: info
  pattern:
    console: "%-6r %d{ISO8601} %highlight(%-5level) [%blue(%t)] %yellow(%X{correlationId}) %magenta(%C{1}): %msg%n%throwable"

# Actuator endpoints
management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,metrics,startup,prometheus"
  info:
    env.enabled: true
    git:
      mode: full
    java.enabled: true
    os.enabled: true

server:
  servlet:
    context-path: /bp/api

spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  flyway:
    schemas: bp_database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: bp_database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        temp.use_jdbc_metadata_defaults: false
        jdbc.time_zone: UTC
    show-sql: false
  messages:
    basename: messages/messages
  profiles:
    active: ${profiles_active:local}
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
