#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS $POSTGRES_DB;
	CREATE USER $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
	ALTER USER $POSTGRES_USER SET search_path TO bp_database;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
	GRANT ALL PRIVILEGES ON SCHEMA $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
