version: "3.0"
services:
  postgres:
    image: postgres:17
    container_name: bp_postgres
    networks:
      - bp_network
    environment:
      POSTGRES_USER: bpuser
      POSTGRES_PASSWORD: bppassword
      POSTGRES_DB: bp_database
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/scripts:/docker-entrypoint-initdb.d:ro
networks:
  bp_network:
    driver: bridge
